### ISSUE TITLE
Error "JSON Editor not ready yet. Listen for 'ready' event before setting the value"

### ISSUE THREAD

**Issue by drsdre** [beowulfenator/yii2-json-editor#2]
When external references are used, setting the initial value is done too early which gives the error message ""JSON Editor not ready yet. Listen for 'ready' event before setting the value". Instead the on "ready" event should be used to set the initial value.

I've added pull request #1 which fixes this. Please have a look for merging.

Andre

**Comment by beowulfenator** [comment]
Thanks.
